### ISSUE TITLE
Contacts without name are not clickable

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#108]
This issue is not that hard, and I've opened it as an invitation for *first-timers* to jump-in the project and do their first contribution.

That means that I will only accept a PR (Pull Request) for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-)

Don't worry, I'll be happy to help you with:

  * Installing timegrid on your local environment for development
  * Explaining the basics about the application and how it works
  * Run tests
  * Change the code and run the tests again
  * Commit the changes and push to your fork
  * Create a PR

Just [reach me on gitter](gitter.im/alariva/timegridDevelopment)

## The issue:

> Contacts without *firstname* nor *lastname* are not clickable.

Example Location: `http://localhost:8000/example/manage/contact`

![Contact not clickable on addressbook](https://cloud.githubusercontent.com/assets/3021314/20165253/4c1d336c-a6ea-11e6-94fa-c6456bc53d6f.jpg)

Affected file:

https://github.com/timegridio/timegrid/blob/master/resources/views/manager/contacts/index.blade.php#L108

Of course there are many ways to go around it. We'll tackle it the simplest way possible and address future enhancements for avoiding the generation of "*nameless*" contacts.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39112519-contacts-without-name-are-not-clickable?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github)

**Comment by calvincanas** [comment]
How about adding links to email and mobile number column or maybe adding a new column with all "actions" button on it?

**Comment by alariva** [comment]
Both options seem to be good ones.

Adding a button is a good one, but requires more horizontal space and that is bad for small screens.
Adding links to email and number are good options, but make a bit more difficult to do copy&paste of those fields.
A third option is to render a generic linking text or element when the string is empty, something distinguishable.

**Comment by calvincanas** [comment]
How about the work "blank"?

or a small workaround with javascript that when the row is clicked it will go to the link: http://stackoverflow.com/a/4904983/3152290

**Comment by alariva** [comment]
Linking the entire row would be nice as well, probably the most intuitive and easy way to handle the addressbook. I wonder if copying the columns data would still be easy enough, but we can give it a try.

**Comment by calvincanas** [comment]
Copying columns data became hard on that approach. Maybe replacing empty values will be the best, copy-wise?

**Comment by alariva** [comment]
Replacing the empty value seems like the simplest solution, we can go with that.

The only conditions are:
  * Should be a string easy to identify as meaning *null* or *missing* or *N/D* in any language (we can also use `trans()`).
  * Should place the items on top or bottom of the list when sorted (with javascript)
  * We could also use just a stmbol like `#`

**Comment by calvincanas** [comment]
How about _n/a_ or meaning not available as you can see [here](https://en.wikipedia.org/wiki/N/a)

**Comment by alariva** [comment]
So it could be `#N/A` in order to send to list extremes when sorting out and make easier to identify visually.

**Comment by calvincanas** [comment]
Yes, will work on this now.
