### ISSUE TITLE
Add clickable client name on schedule table view

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#112]
This issue is not that hard, and I've opened it as an invitation for *first-timers* to jump-in the project and do their first contribution.

That means that I will only accept a PR (Pull Request) for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-)

Don't worry, I'll be happy to help you with:

  * Installing timegrid on your local environment for development
  * Explaining the basics about the application and how it works
  * Run tests
  * Change the code and run the tests again
  * Commit the changes and push to your fork
  * Create a PR

Just [reach me on gitter](https://gitter.im/alariva/timegridDevelopment)

## The issue

> The schedule view should display the client name and link to his profile, even when te contact has no firstname and lastname set.

Related to #109 

![Missing Contact name on schedule view](https://cloud.githubusercontent.com/assets/3021314/20194949/3a26e796-a773-11e6-843a-ec46a29574ac.jpg)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39135581-add-clickable-client-name-on-schedule-table-view?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github).

**Comment by jaalsh** [comment]
Hey. I'd like to this issue please.

**Comment by alariva** [comment]
Hi @jaalsh , go ahead, any info/help you need please reach me on [Gitter](https://gitter.im/alariva/timegridDevelopment)

**Comment by jaalsh** [comment]
It appears I won't have access to a computer for a few days. Someone else can take this if they want.
