### ISSUE TITLE
Broken post registration

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#115]
Registration process throws error after post.

This is after upgrading to Laravel 5.3, still some stuff pending to wire-up regarding authentication.

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39157320-broken-post-registration?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F25917617&utm_medium=issues&utm_source=github).

**Comment by alariva** [comment]
In `.env` file the `CACHE_DRIVER=` should not be `file` as it does not support tagging (and raises `'BadMethodCallException' with message 'This cache store does not support tagging.'`)

**Comment by calvincanas** [comment]
I made mine _array_ to make the site work.

**Comment by alariva** [comment]
Thanks @calvincanas . I did the same, and that's fine for local and testing environments, but I think it should be something else for production, like `memcached`. This issue however is already addressed.

**Comment by calvincanas** [comment]
Nice to hear!
