### ISSUE TITLE
Unfriendly error on /home page when unauthenticated

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#116]
This exception is thrown when an unregistered user visits `/home`, should be redirected to login page.

`ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function hasBusiness() on null' in .../app/Http/Controllers/User/WizardController.php:29 Stack trace: #0 {main}`

Probably a *middleware* related issue.

**Comment by achrafkh** [comment]
i worked on this, i will make a pull request for it

**Comment by sahilsharma011** [comment]
Is this still up for grabs? This can easily be fixed by assigning `auth` middleware to this route. I can make a PR if no one is doing it
