### ISSUE TITLE
Fix long description line display on business listing directory

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#124]
This issue is not that hard, and I've opened it as an invitation for *first-timers* to jump-in the project and do their first contribution.

That means that I will only accept a PR (Pull Request) for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-)

Don't worry, I'll be happy to help you with:

  * Installing timegrid on your local environment for development
  * Explaining the basics about the application and how it works
  * Run tests
  * Change the code and run the tests again
  * Commit the changes and push to your fork
  * Create a PR

Just [reach me on gitter](https://gitter.im/alariva/timegridDevelopment)

## The issue

Self explainatory too-long-line (without spaces).

![issue-long-line-no-spaces-business-directory](https://cloud.githubusercontent.com/assets/3021314/20240935/92580836-a904-11e6-80ff-dbbae26b74dc.png)

[Affected view file line](https://github.com/timegridio/timegrid/blob/master/resources/views/user/businesses/_row.blade.php#L16)

**Comment by niharikak101** [comment]
Hi there! The gitter link doesn't seem to be working, but I'd love to help out. :)

**Comment by alariva** [comment]
Hi @niharikak101 , sorry! my bad! I fixed the link... but here a fancy one just in case :)

[![Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg?maxAge=2592000?style=flat-square)](https://gitter.im/alariva/timegridDevelopment)

**Comment by alariva** [comment]
[This info regarding HTML and CSS may help](http://stackoverflow.com/questions/499137/css-how-can-i-force-a-long-string-without-any-blank-to-be-wrapped-in-xul-and), but try not to use inline `style` atrribute on html tags. (Dont hestiate to ask on Gitter and we'll find a clean solution)

**Comment by alariva** [comment]
Before

![screenshot from 2016-11-14 19 13 51](https://cloud.githubusercontent.com/assets/3021314/20285113/f231caf8-aa9e-11e6-9d01-dbcf744721f8.png)

After

![screenshot from 2016-11-14 19 16 00](https://cloud.githubusercontent.com/assets/3021314/20285124/faddfa5a-aa9e-11e6-83d6-e5bd4a8f11b8.png)
