### ISSUE TITLE
Exception 'ReflectionException' with message 'Class App\Listeners\SendSofAppointmentValidationRequest does not exist'

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#139]
> Easy typo fix on a symbol. This means huge affection (bug) and easy fix.

This issue is not that hard, and I've opened it as an invitation for *first-timers* to jump-in the project and do their first contribution.

That means that I will only accept a PR (Pull Request) for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-)

Don't worry, I'll be happy to help you with:

  * Installing timegrid on your local environment for development
  * Explaining the basics about the application and how it works
  * Run tests
  * Change the code and run the tests again
  * Commit the changes and push to your fork
  * Create a PR

Just [reach me on gitter](https://gitter.im/alariva/timegridDevelopment)

**How to reproduce:**

Go to a business homepage as *guest* (unauthenticated user), perform an appointment reservation. You will be required to enter an email address. Use an email that is not previously registered. After confirmation, the appointment will be taken, however, the user get's an error message. Captured exception below.

**Exception:**

```
demo.timegrid[22297]: demo.INFO: Appointment saved successfully [] []
demo.timegrid[22297]: demo.ERROR: exception 'ReflectionException' with message 'Class App\Listeners\SendSofAppointmentValidationRequest does not exist' in /var/www/timegrid/bootstrap/cache/compiled.php:1375

Stack trace: 
#0 /var/www/timegrid/bootstrap/cache/compiled.php(1375): ReflectionClass->__construct('App\\Listeners\\S...') 
#1 /var/www/timegrid/bootstrap/cache/compiled.php(1329): Illuminate\Container\Container->build('App\\Listeners\\S...', Array) 
#2 /var/www/timegrid/bootstrap/cache/compiled.php(1907): Illuminate\Container\Container->make('App\\Listeners\\S...', Array) 
#3 /var/www/timegrid.io/demo/htdocs/bootstrap/cache/compiled.php(10150): Illuminate\Foundation\Application->make('App\\Listeners\\S...') 
#4 /var/www/timegrid/bootstrap/cache/compiled.php(10141): Illuminate\Events\Dispatcher->createClassCallable('App\\Listeners\\S...', Object(Illuminate\Foundation\Application)) 
#5 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\NewSoftAppointmentWasBooked)) 
#6 /var/www/timegrid/bootstrap/cache/compiled.php(10081): call_user_func_array(Object(Closure), Array) 
#7 /var/www/timegrid/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(477): Illuminate\Events\Dispatcher->fire(Object(App\Events\NewSoftAppointmentWasBooked)) 
#8 /var/www/timegrid/app/Http/Controllers/User/AgendaController.php(204): event(Object(App\Events\NewSoftAppointmentWasBooked)) 
#9 [internal function]: App\Http\Controllers\User\AgendaController->postStore(Object(Illuminate\Http\Request), 'business') 
#10 /var/www/timegrid/bootstrap/cache/compiled.php(9399): call_user_func_array(Array, Array) 
#11 /var/www/timegrid/bootstrap/cache/compiled.php(9426): Illuminate\Routing\Controller->callAction('postStore', Array) 
#12 /var/www/timegrid/bootstrap/cache/compiled.php(8484): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\User\AgendaController), 'postStore') 
#13 /var/www/timegrid.io/demo/htdocs/bootstrap/cache/compiled.php(8465): Illuminate\Routing\Route->runController() 
#14 /var/www/timegrid/bootstrap/cache/compiled.php(8174): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) 
...
```

**Comment by Kashyap12** [comment]
Hi @alariva I am working on this

**Comment by alariva** [comment]
Also fixed a bad view path reference so the entire use case of soft appointments with unregistered email is solved.
