### ISSUE TITLE
Add language picker on landing page

### ISSUE THREAD

**Issue by alariva** [timegridio/timegrid#140]
That's it.

Timegrid will attempt to serve the page on the browser's preferred language, however, the user may still want to switch language, and there is no way to do it from landing page.

**Comment by sahilsharma011** [comment]
Are you talking about the home page?

**Comment by alariva** [comment]
Yes, right in the landing page `/`.

Timegrid will try to detect the preferred language from browser, but sometimes the user will want to switch manually.

**Comment by alariva** [comment]
Added
