### ISSUE TITLE
Feature request: Sandstorm support

### ISSUE THREAD

**Issue by rawray7** [timegridio/timegrid#148]
it would be awesome to see this available on the sandstorm platform - https://github.com/sandstorm-io/sandstorm

no idea how much work that would be, just a thought!

**Comment by alariva** [comment]
Thanks for the hint. I'm not aware of what exactly would it take, could you debscribe the benefits of this feature?

So far timegrid provides a dockerfile for building your development environment in minutes.

**Comment by rawray7** [comment]
it's a really incredible platform for self-hosted apps and i think timegrid would fit really nicely there. the benefit would be that it would be integrated with their authorization system, and be a one-click install for people on that platform. (pinging @jadeqwang)

**Comment by alariva** [comment]
Thanks for clarification. However I still don't get what actual changes on timegrid's codebase are you requesting for this feature?

**Comment by alariva** [comment]
Feel free to jump in [Gitter channel](https://gitter.im/alariva/timegridDevelopment) so we can discuss on this.

Closing for now.
