### ISSUE TITLE
Enhancement : Add logout button for user in navbar

### ISSUE THREAD

**Issue by sahilsharma011** [timegridio/timegrid#156]
There is no logout button on `/home` route. What if the user wants to logout from home?

**Comment by alariva** [comment]
Agree. Is it kind of linked to #119 ?

**Comment by sahilsharma011** [comment]
I am asking for a logout button on the top right here
![image](https://cloud.githubusercontent.com/assets/9516206/21283647/071bfd66-c42c-11e6-837f-65911264cfd5.png)
<br><br>
Like this
![image](https://cloud.githubusercontent.com/assets/9516206/21283653/160ca58c-c42c-11e6-8f43-143a7128f207.png)

**Comment by alariva** [comment]
Right. Not related, agree with observation :)
