### ISSUE TITLE
Bug : Redundant closing tag for footer

### ISSUE THREAD

**Issue by sahilsharma011** [timegridio/timegrid#157]
`</footer>` is included twice in following files : 

-  View [layouts/bare](https://github.com/timegridio/timegrid/blob/master/resources/views/layouts/bare.blade.php)
- View [layouts/public](https://github.com/timegridio/timegrid/blob/master/resources/views/layouts/public.blade.php)
- View [layouts/user](https://github.com/timegridio/timegrid/blob/master/resources/views/layouts/user.blade.php)

**Comment by alariva** [comment]
Was not aware of this, thanks for pointing out!
