### ISSUE TITLE
Issue with running dockerfiles 

### ISSUE THREAD

**Issue by ududsha** [timegridio/timegrid#164]
`Unable to find image 'timegrid:latest' locally `
Above error occurred when I run [dockerfiles ](https://github.com/timegridio/dockerfiles). Help me to fix this issue.

**Comment by alariva** [comment]
Hi @ududsha , did you follow all the steps on https://github.com/timegridio/dockerfiles ?

Whats the output of `sudo docker images` ?

Or jump to [Gitter](gitter.im/alariva/timegridDevelopment) to discuss step-by-step.
