### ISSUE TITLE
Industry blank on registeration

### ISSUE THREAD

**Issue by CokkocZateki** [timegridio/timegrid#169]
Hi.
I installed timegrid onto my server and im trying to create an premium contract (/user/businesses/register/premium)

i fill out the fields however the industry section shows no result found. any idea how to work around this?

![image](https://cloud.githubusercontent.com/assets/16074209/25313951/dc7f8402-2839-11e7-9437-604b42190699.png)

**Comment by alariva** [comment]
Hi,

Did you run `php artisan db:seed` during [Installation](https://github.com/timegridio/timegrid/blob/master/INSTALLING.md#step-4-configure-the-environment) ?

A sample Industry Category set will be inserted into DB:

See:

https://github.com/timegridio/timegrid/blob/master/database/seeds/DatabaseSeeder.php

https://github.com/timegridio/timegrid/blob/master/database/seeds/CategoriesSeeder.php

**Comment by CokkocZateki** [comment]
that did the trick. im so sure i ran the `php artisan db:seed` . but nonetheless it worked. thanks @alariva
