### ISSUE TITLE
Creating a new business using GUI

### ISSUE THREAD

**Issue by jeromecc** [timegridio/timegrid#173]
Type Of Issue: Question
Timegrid environment: local install
Browser Name and Version: Firefox 52.0.2
Server Operating System: Debian 9 Stretch
Hello!

I installed TimeGrid 24 hours ago using code from the master branch and following https://github.com/timegridio/timegrid/blob/master/INSTALLING.md except for the demo sandbox:
I used an alternative version

    php artisan db:seed --class=TestingDatabaseSeeder2

derived from TestingDatabaseSeeder that contains only one CreateDemoManagerUser() function and nothing else.

I can create a first business without any problem and everything seems to work fine, but I couldn't find a way to create a 2nd business with this manager user.

I know I could create it with another seeding php file, but how can I create it from the web interface?

Thanks.

**Comment by jeromecc** [comment]
In fact it's not a local install, it's an online install: http://timegrid.webmedecin.net

**Comment by alariva** [comment]
Hi @jeromecc , thanks for pointing out this question.

Given that you are already logged in, look for the rightmost top-nav menu item (with your avatar and username).

  - Click to dropdown.
  - Click *My Businesses*. You will be sent to a new screen listing your registered businesses.
  - Click *SignUp Business*. You will be sent to the business registration form.

Hope this helps

**Comment by jeromecc** [comment]
Thank you. Please review pull request for documentation: https://github.com/timegridio/docs/pull/3
