### ISSUE TITLE
\bootstrap\autoload.php on line 17 -- 

### ISSUE THREAD

**Issue by Ammar777** [timegridio/timegrid#176]
the error message

C:\Users\One_1\Desktop\timegrid-master\timegrid-master>php artisan key:generate
```
Warning: require(C:\Users\One_1\Desktop\timegrid-master\timegrid-master\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Users\One_1\Desktop\timegrid-master\timegrid-master\bootstrap\autoload.php on line 17
```

**Comment by alariva** [comment]
Hi @Ammar777 , did you follow all the steps on https://github.com/timegridio/timegrid/blob/master/INSTALLING.md and verified the https://github.com/timegridio/timegrid/blob/master/TROUBLESHOOTING.md section?
