### ISSUE TITLE
User Scheduling issue 

### ISSUE THREAD

**Issue by JVitorst** [timegridio/timegrid#180]
I'm having this unforeseen time to schedule.
![screen](https://user-images.githubusercontent.com/5400769/28492753-55dd7ed0-6edf-11e7-8b08-c89e7dfa3d64.gif)

In my developer tools:
![timegrid](https://user-images.githubusercontent.com/5400769/28492914-464a6408-6ee2-11e7-825c-f86af32d31b4.PNG)

Thanks for the time.
And congratulations on the project, that's great.

**Comment by alariva** [comment]
Hi, thanks for reporting this and the nice words.

I dont know what set of vacancies (availability) have you published. There are many things to check about that, but, are you using the same timezone for the business manager and the cliet user?

**Comment by Henshall** [comment]
IM getting the same error. It looks like this app is incomplete

**Comment by alariva** [comment]
@JVitorst, please try by changing the preference **Availability Future Days**

![image](https://user-images.githubusercontent.com/3021314/75560105-5aaf1400-5a23-11ea-900b-2615812a6c92.png)
