### ISSUE TITLE
Error LOG

### ISSUE THREAD

**Issue by acelinosilva** [timegridio/timegrid#186]
hello, my is giving the error Fatal error: Class 'Log' not found in C: \ wamp \ www \ app \ timegrid \ app \ Exceptions \ Handler.php on line 43 when I put the php artisan migrate in instalation

**Comment by alariva** [comment]
Hi @omagoobscuro , it looks like a step might be missing on installation process. Have you followed the INSTALLING instructions step-by-step and made sure system requirements are all met?
