### ISSUE TITLE
Running the project

### ISSUE THREAD

**Issue by Rangnarer** [timegridio/timegrid#187]
I am trying to run the project. Sorry there is a part 3 in the installation guide - Create Database, but there is not specified what the of the database need to be. Could you tell me it, please.

**Comment by alariva** [comment]
Hi @Rangnarer , thanks for pointing that out. I'll add that info.

I'm using MySQL (5.7) so one proper configuration, assuming that your database is in the same host and you call the user with the same name as the database and password is "password" could be:

```
DB_HOST=localhost
DB_DATABASE=timegrid
DB_USERNAME=timegrid
DB_PASSWORD=password
```

**Comment by shifatbuet** [comment]
Check the instruction .

Create database with any name with collation utf8_general_ci.

Change your .env file accordingly.
