### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Propaganistas\LaravelIntl\IntlServiceProvider' not found 

### ISSUE THREAD

**Issue by chen890** [timegridio/timegrid#190]
Fatal error: Uncaught Error: Class 'Propaganistas\LaravelIntl\IntlServiceProvider' not found 
what should be the problem?

**Comment by chen890** [comment]
@alariva

**Comment by alariva** [comment]
Hi, a fresh install from the master branch should not throw that error.

**Comment by chen890** [comment]
@alariva can you show it to me? I'm kind a new at this...
I did it step by step like in this manual: https://github.com/timegridio/timegrid/blob/master/INSTALLING.md

**Comment by alariva** [comment]
Make sure that the `Propaganistas\LaravelIntl\IntlServiceProvider` is not listed in `config/app.php` in `providers` section. It shouldn't be installed. If it is, that's not a fresh install of timegrid.
