### ISSUE TITLE
Call to undefined function locale_get_primary_language()

### ISSUE THREAD

**Issue by chen890** [timegridio/timegrid#191]
@alariva 
how to fix this?

**Comment by alariva** [comment]
Please refer to https://github.com/timegridio/timegrid/blob/6acf09612a82b12018d7f7f7277ae1bb3fdf7826/TROUBLESHOOTING.md#call-to-undefined-function-locale_get_primary_language

**Comment by chen890** [comment]
@alariva
I dont know how to install PHP intl
can you give a direct download and tell me where to store it? how to save it and where?

**Comment by chen890** [comment]
@alariva please help me out here, I'm lost..

**Comment by alariva** [comment]
Please follow instructions on PHP docs: https://www.php.net/manual/en/intl.installation.php

**Comment by chen890** [comment]
@alariva I have view on the instructions but I dont know what to do with the zip file ([](https://pecl.php.net/get/intl-3.0.0.tgz)) I download from: [](https://pecl.php.net/package/intl)
the file name is: 

Version | State | Release Date | Downloads |  
-- | -- | -- | -- | --
stable | 2013-06-02 | intl-3.0.0.tgz (242.4kB)

What should I do next?

**Comment by alariva** [comment]
What platform are you running? Win/Linux/Mac?

**Comment by chen890** [comment]
Windows @alariva

**Comment by chen890** [comment]
@alariva I'm using Windows 10

**Comment by alariva** [comment]
Please check if following these instructions help

https://www.dotkernel.com/php-troubleshooting/where-is-the-intl-php-extension-problem-solved/
