### ISSUE TITLE
How install without Composer

### ISSUE THREAD

**Issue by caygri** [timegridio/timegrid#192]
Hello,

is possible install without composer? Maybe just on plesk/cpanel?

thank you

**Comment by alariva** [comment]
Hi,

I'm not sure if the project is suitable for `plesk/cpanel`. Feel free to try that out yourself.

Timegrid is an application built with [Laravel](https://laravel.com/). The install process is very similar, and requires composer at build time.

That said, I suggest you [reading this SO question](https://stackoverflow.com/questions/15940140/can-i-install-laravel-without-using-composer).

TLDR; You may run composer in your local machine, then upload the entire project with the `vendor/` dir contents as well.

**Comment by caygri** [comment]
Helllo, with plesk there is an extention to install. It's very easy and called PHP Composer. After installed of extension, go in domain and click on icon "PHP Composer", confirm to analyze Composer App and wait few minute. 

Suggestion to install all dipendencies, configure env file and Timegrid is install :D
