### ISSUE TITLE
Bug: Timezone for new location

### ISSUE THREAD

**Issue by annylinh08** [timegridio/timegrid#195]
Hi everyone, I just downloaded and tested this project on my localhost when I make a reservation as a guest with a business I have created having Eastern Time. I got this issue
![timezone](https://user-images.githubusercontent.com/47993207/75553275-13665a80-5a06-11ea-9fde-c1a0d899b677.PNG)

Could anyone know where to fix it?

**Comment by alariva** [comment]
Related to #170

**Comment by alariva** [comment]
This problem is due to obsolete timezones listed in timegrid.

https://www.php.net/manual/en/timezones.others.php

An update of the list is going to take place to fix it.

**Comment by alariva** [comment]
@annylinh08 , please upgrade your local application to latest in master, then follow the steps to re-configure.

# 1 - Upgrade your application and update dependencies

```
git pull
composer install
```

# 2 - Go to the edit business page, and re-configure the timezone by selecting the provided option.

![image](https://user-images.githubusercontent.com/3021314/75559359-11aa9000-5a22-11ea-866d-df9aea9b4f09.png)

# 3 - Try to reproduce the issue (setting service vacancies)

The error should not appear this time.

---

Should you require further assistance, please join the [Gitter Chat Room](https://gitter.im/timegrid-development/community) to opensource the discussion.

Thanks!
