### ISSUE TITLE
Make the users' comment visible

### ISSUE THREAD

**Issue by annylinh08** [timegridio/timegrid#200]
Hi there, 
When we make the reservation, there is a field called "Would you like to leave any comments for the provider?". However, I found that this comment doesn't show up anywhere in the admin dashboard
![image](https://user-images.githubusercontent.com/47993207/75938060-b5e26b80-5e54-11ea-8b44-52671825c18a.png)
![image](https://user-images.githubusercontent.com/47993207/75938130-f5a95300-5e54-11ea-97e9-a3706ef6c579.png)
Could anyone make it visible?

**Comment by alariva** [comment]
Now comments are added as an icon next to the Service name.

![image](https://user-images.githubusercontent.com/3021314/75998519-b83dd780-5edf-11ea-9045-a1723a22ca51.png)

![image](https://user-images.githubusercontent.com/3021314/75998464-a825f800-5edf-11ea-908c-ed307f958548.png)
