### ISSUE TITLE
AGPL licence?

### ISSUE THREAD

**Issue by dangerdan** [timegridio/timegrid#202]
Hello,

Is the AGPL licence intentional? I'd like to consider to use some elements of this project, but the license is too restrictive for mine, and I suspect others, current needs. Any chance of MIT or similar?

**Comment by alariva** [comment]
Hi @dangerdan ,

The AGPL seemed to be a good fit for a SaaS application like Timegrid. However, some components of the application are external packages that are licenced with MIT. Let me know which pieces would you require so I can check if anything could be done to help.

Thanks!

**Comment by dangerdan** [comment]
Well i'd like to use timegrid as a backend whilst paying for a mobile front-end app to be created. My understanding of AGPL means i'd have to release all of this enhancement code in order to use the timegrid code?

**Comment by alariva** [comment]
That's correct, in case you'd enhance the code it must be publicly available within the AGPL license and preserving it's original authorship.

**Comment by dangerdan** [comment]
Ok. I don't think that will work. Especially if I wanted to update this to use proprietary code like Laravel Spark, which I'd legally be unable to release. Best of luck with the project.
